name: Unit Tests

on: 
  push:
    branches:
      - '*'
      - '!gh-pages'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm install
    - name: Run tests coverage
      run: npm run cov
      env: # Or as an environment variable
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
    - uses: codecov/codecov-action@v1.2.1
      with:
        flags: unittests 
        name: codecov-tadashi
        fail_ci_if_error: true 
    - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          files: "tset-results.xml"
